### ISSUE TITLE
It looks like not woking 29.970 fps source.

### ISSUE THREAD

**Issue by fingul** [Dash-Industry-Forum/dash-live-source-simulator#107]
Hi!

Does this program support 29.970 fps source?

It looks like not woking 29.970 fps source.

**Comment by TobbeEdgeware** [comment]
@fingul. Sorry for the late response.

One cannot run 29.97Hz video easily with this tool. It was designed to run sequences that have a segment duration which is an integral number of seconds in average and have a number of segments that make both video and audio wrap exactly.

This cannot be achieved with a fixed GoP duration for 29.97Hz video, but possibly with varying GoP/segment duration. 

In particular you could have a 4004s long video 2002 segments of average duration 2s alternating between 60 and 61 frames. To make the audio wrap properly, it would need to be something like 32kHz AAC-LC. For 48kHz AAC, a multiple of 8s is needed.

If you can create such a sequence, it should be possible to have it loop properly without any drift. I haven't tried it though.

A disadvantage of having a 4004s sequence instead of the default 3600s which wraps every hour is that one cannot easily relate the clock in the video to wall-clock time.
