### ISSUE TITLE
parse error when SegmentTemplate in subnode of Representation

### ISSUE THREAD

**Issue by pengzhisheng** [Dash-Industry-Forum/dash-live-source-simulator#114]
example manifest file:
[Manifest.txt](https://github.com/Dash-Industry-Forum/dash-live-source-simulator/files/9934523/Manifest.txt)

**Comment by tobbee** [comment]
Your issue is without context so I don't know exactly where it applies, but it may happen that the dashanalyzer doesn't accept a SegmentTemplate inside a Representation. In general, it is not a general DASH MPD parser, but quite picky about the content. Having the SegmentTemplate inside a Representation makes it harder to compare with other Representations in the same AdaptationSet, so for adaptive bitrate is is normally better to have one SegmentTemplate on AdaptationSet level for all Representations.

If you want use a specific content, I'd suggest that you tweak the MPD and move the SegmentTemplate to the AS level and check if you get any further.
