### ISSUE TITLE
publishTime missing

### ISSUE THREAD

**Issue by joywelt** [Dash-Industry-Forum/dash-live-source-simulator#20]
According to the standard and the conformance software, if MPD is of type "dynamic" publishTime shall be defined. It's currently missing in develop and feature-segment-timeline (maybe also other) branches.

**Comment by joywelt** [comment]
The plan is to use availabilityStartTime as publishTime for single period content. For multiple period content, the publishTime shall be defined as the start time of the last period. 
Any other ideas?

**Comment by waqarz** [comment]
"availabilityStartTime as publishTime for single period content" I think you said the other way around: publishTime would be the availabilityStartTime for a single period.

We could say in general that publishTime is aligned to the start time of the lastest period ...?

**Comment by TobbeMobiTV** [comment]
publishTime was not mandatory when the dash-live-source-simulator was first written. The manifest validator even complained if it was added (as it was it was at some time).

The publishTime should reflect the date of the latest MPD change. For one-period content publishTime=AST should be fine. For multiperiod content it should reflect the time where the MPD changes which is not at the period boundary, but before that (enough time so that polling with minimumUpdatePeriod works).

Please make a proposal on how to add it, but make sure that the namespace is update in accordance (if it needs to be).

**Comment by waqarz** [comment]
"For multiperiod content it should reflect the time where the MPD changes which is not at the period boundary, but before that (enough time so that polling with minimumUpdatePeriod works)."

Right, so then could it be generalized to: PublishTime = (Live edge time) - (Live edge time)%minimumUpdatePeriod ..?

"but make sure that the namespace is update in accordance"

Not sure what do you mean, what needs to be done?

**Comment by waqarz** [comment]
Or probably easier approximation: PublishTime = (time now) - (time now)%minimumUpdatePeriod

**Comment by TobbeMobiTV** [comment]
@waqarz  I don't think that is a good approach. In my view, publishTime should only change if the manifest does. Otherwise, there may be a complete parsing in the client just to find out that nothing has changed.

**Comment by waqarz** [comment]
@TobbeMobiTV OK, so we need to estimate this in the emulator, i.e. publish time would be the time instance the live emulator generates a different MPD from the previous instance of time. This is why I was relating it to period start, wouldn't it be the start time of the period in which time now falls in? I am not sure if its implemented differently.

**Comment by waqarz** [comment]
Oh, yes, we need to subtract one MUP from that value.

**Comment by waqarz** [comment]
We're checking this on our end, will post update.

**Comment by joywelt** [comment]
Is it sufficient to use PublishTime = (time now) - (time now)%minimumUpdatePeriod - MUP?
When /mup_x/ is not present in the URL, then we use DEFAULT_SHORT_MINIMUM_UPDATE_PERIOD_IN_S (10s).

**Comment by waqarz** [comment]
@joywelt , as we just discussed: there exists a partial implementation already in the code, please propose an initial implementation update as an example.

**Comment by TobbeMobiTV** [comment]
Just wanted to mention that there is a mode of the simulator which has MPD updates and even periods when no content is available, but will be soon again. In such cases, the publishTime is before the AST which is in the future.

A test URL is

http://vm2.dashif.org/livesim/modulo_10/testpic_2s/Manifest.mpd 

and the module_X mode is described as **Dynamic MPD with static URLs** on https://github.com/Dash-Industry-Forum/dash-live-source-simulator/wiki

The publishTime should be the time when the "state" of the MPD generator changes.

I'll spend my time on getting SegmentTimeLine a bit further today. I hope to get back to this issue tomorrow.

**Comment by TobbeEdgeware** [comment]
I added the most simplistic publishTime implementation in commit 4572ddd by adding the current DateTime, and haven't had time to come back to this.. However, when looking at singling Manifest update according to the SAND specification as well as the part 1 of the standard, it is obvious that it is important that the manifest has a "constant" publishTime that can be referred to. Thus, I think one should go through every principal mode of the live simulator and make sure to only update the publishTime when the MPD content changes. There should be two tests for each case to make sure that the change in publishTime is done at the right time instance.

**Comment by TobbeEdgeware** [comment]
I've created a new issue #40 for an improved implementation.
