### ISSUE TITLE
minimumUpdatePeriod (mup_x)

### ISSUE THREAD

**Issue by vto5623** [Dash-Industry-Forum/dash-live-source-simulator#50]
Hi,
I have been trying to use this kind of url recently, but the "mup_30" parameter does not seem to be applied properly (keep getting minimumUpdatePeriod="PT0S" in the manifest).
https://vm2.dashif.org/livesim-dev/utc_direct/mup_30/segtimeline_1/periods_20/testpic_6s/multiaudio.mpd
Am I doing something wrong?

Thanks

**Comment by TobbeEdgeware** [comment]
Minimum update period is not enabled for SegmentTimeLine. I have a hard to time to see why it should be meaningful to have anything else than a segment duration (or zero), since the manifest is updated with every segment. For the template case with $Number$ it should work to change minimumUpdatePeriod to any value.

Still, it should probably be possible to set the value also for SegmentTimeline, at least to 2s or whatever the segment duration is, but from an implementation point of view, it should be simple to set it to any value.
