### ISSUE TITLE
Simulator seems to be down

### ISSUE THREAD

**Issue by joeyparrish** [Dash-Industry-Forum/dash-live-source-simulator#8]
http://vm2.dashif.org/ seems to be down at the moment.  Is this intentional?  Will it be back any time soon?

**Comment by TobbeMobiTV** [comment]
No, it was not intentional, but it is available again with another IP address.

The Amazon VM running this server stalled (100% CPU and not accessible) and needed to get restarted. It then got a new public IP address, and it took a while to get the DNS entry updated. The VM has now an "elastic IP address" so the address should not change again.

**Comment by KozhinM** [comment]
@TobbeMobiTV, I still have issues with accessing the recourse. For example, I am trying to play the following mpd and have the mpd request aborted (after pending for a while):
http://vm2.dashif.org/livesim/testpic_6s/Manifest.mpd
Could you please confirm that the VM is working properly?

**Comment by TobbeMobiTV** [comment]
Sorry, I had a cached page, so I thought it was working.

The new IP address is 52.26.13.114.

Please try to use that until the DNS is fixed
(Will has asked for it, but apparently it is not yet done).

**Comment by KozhinM** [comment]
@TobbeMobiTV, it works with the new IP, thanks!

**Comment by TobbeMobiTV** [comment]
Now the DNS is fixed. Sorry for the delay.
